"""A synthetic talker, for testing the speaker verifier without recordings.

The verifier's claim is that it separates people by the two things a classical
verifier can see: the resonances of their vocal tract and the pitch of their
larynx. So the test signal is generated by a source-filter model, which is the
same claim written as a synthesiser — a glottal pulse train at F0, jitter and
shimmer on it, through a cascade of formant resonators, plus breath noise.

**These are not human voices and no test here claims they are.** What they can
settle is whether the code separates signals that differ in exactly the cues it
says it uses, and whether it holds two utterances of the *same* synthetic
speaker together despite different words, lengths and levels — which is the
failure mode a threshold has to survive. Accuracy against real speech is marked
Unproven in `docs/verification.md`, because a build machine cannot settle it.

Everything is seeded. A flaky biometric test is worse than no biometric test:
it teaches you to re-run it.
"""

from __future__ import annotations

import math
import random
from array import array
from dataclasses import dataclass, field

RATE = 16000


@dataclass(frozen=True)
class SynthSpeaker:
    """One synthetic talker: a pitch, a vocal tract, and how breathy they are."""

    name: str
    f0: float
    #: Formant centre frequencies in Hz. Three is enough to make a vowel
    #: identifiable and to make two speakers measurably different.
    formants: tuple[float, ...]
    #: Formant bandwidths — how damped the resonances are. A wider bandwidth
    #: is a "softer" voice and it moves the spectral envelope independently of
    #: where the formants sit.
    bandwidths: tuple[float, ...] = (90.0, 110.0, 170.0)
    #: Breath noise mixed in with the glottal source, 0..1.
    breathiness: float = 0.06
    #: Cycle-to-cycle pitch wobble, as a fraction of F0.
    jitter: float = 0.015

    def utterance(
        self,
        seconds: float = 2.5,
        *,
        seed: int = 0,
        gain: float = 0.35,
        f0_scale: float = 1.0,
    ) -> bytes:
        """One utterance as 16 kHz mono int16 PCM.

        `seed` changes the "words": which vowels, in what order, with what
        pauses. `f0_scale` moves the whole utterance's pitch, standing in for
        the difference between asking a question and giving an order.
        """
        rng = random.Random(seed * 7919 + int(self.f0))
        total = int(seconds * RATE)
        out = array("h", bytes(2 * total))

        resonators = [_Resonator(f, b) for f, b in zip(self.formants, self.bandwidths)]
        # Vowel-ish segments: the tract is re-tuned every 90-220 ms, which is
        # what makes two utterances of one speaker differ the way words do.
        position = 0
        phase = 0.0
        while position < total:
            length = rng.randint(int(0.09 * RATE), int(0.22 * RATE))
            silent = rng.random() < 0.18
            # A vowel shifts the formants around the speaker's own tract
            # rather than replacing them: that is precisely the distinction
            # the verifier has to survive.
            shift = [rng.uniform(0.82, 1.22) for _ in resonators]
            for index, resonator in enumerate(resonators):
                resonator.retune(self.formants[index] * shift[index], self.bandwidths[index])
            segment_f0 = self.f0 * f0_scale * rng.uniform(0.93, 1.07)

            for offset in range(min(length, total - position)):
                sample_index = position + offset
                if silent:
                    out[sample_index] = int(rng.gauss(0.0, 0.0015) * 32767)
                    continue
                step = segment_f0 * (1.0 + rng.gauss(0.0, self.jitter)) / RATE
                phase += step
                if phase >= 1.0:
                    phase -= 1.0
                    excitation = 1.0
                else:
                    # Rosenberg-ish glottal pulse: a smooth open phase rather
                    # than an impulse, so the source has a realistic -12 dB /
                    # octave tilt instead of a flat spectrum.
                    excitation = -0.4 * math.sin(math.pi * phase) ** 2
                excitation += rng.gauss(0.0, self.breathiness)
                value = 0.0
                for weight, resonator in enumerate(resonators):
                    value += resonator.step(excitation) / (1.0 + weight)
                value *= gain
                out[sample_index] = _clip(value)
            position += length
        return out.tobytes()


class _Resonator:
    """Two-pole resonator — one formant."""

    __slots__ = ("_a1", "_a2", "_gain", "_y1", "_y2")

    def __init__(self, frequency: float, bandwidth: float) -> None:
        self._y1 = 0.0
        self._y2 = 0.0
        self.retune(frequency, bandwidth)

    def retune(self, frequency: float, bandwidth: float) -> None:
        radius = math.exp(-math.pi * bandwidth / RATE)
        theta = 2.0 * math.pi * frequency / RATE
        self._a1 = 2.0 * radius * math.cos(theta)
        self._a2 = -radius * radius
        self._gain = (1.0 - radius) * math.sqrt(1.0 - 2.0 * radius * math.cos(2 * theta) + radius**2)

    def step(self, excitation: float) -> float:
        value = self._gain * excitation + self._a1 * self._y1 + self._a2 * self._y2
        self._y2 = self._y1
        self._y1 = value
        return value


def _clip(value: float) -> int:
    scaled = int(value * 32767)
    return max(-32768, min(32767, scaled))


def whispering(speaker: SynthSpeaker) -> SynthSpeaker:
    """The same talker, breathy enough that their pitch stops being measurable.

    Same larynx, same tract, no usable periodicity — which is the case that
    separates "I could not measure your pitch" from "your pitch is wrong", and
    the one an impostor would reach for if the first were treated as a pass.
    """
    return SynthSpeaker(
        name=f"{speaker.name}-whispering",
        f0=speaker.f0,
        formants=speaker.formants,
        bandwidths=tuple(width * 1.6 for width in speaker.bandwidths),
        breathiness=0.30,
        jitter=speaker.jitter,
    )


#: A cast with real spread: two low-pitched, two high, one in between, and two
#: pairs deliberately close together so the tests are not all easy.
OWNER = SynthSpeaker("owner", f0=118.0, formants=(520.0, 1180.0, 2560.0))
IMPOSTORS = (
    # Far away: much higher pitch, much shorter tract.
    SynthSpeaker("soprano", f0=224.0, formants=(700.0, 1900.0, 3100.0)),
    # Similar pitch, clearly different tract — the honest hard case.
    SynthSpeaker("baritone", f0=112.0, formants=(660.0, 1520.0, 2380.0)),
    # Similar tract, clearly different pitch.
    SynthSpeaker("tenor", f0=168.0, formants=(535.0, 1210.0, 2600.0)),
    # Breathy, wide bandwidths — a different voice quality at a nearby pitch.
    SynthSpeaker(
        "whisperer",
        f0=126.0,
        formants=(600.0, 1400.0, 2700.0),
        bandwidths=(160.0, 220.0, 300.0),
        breathiness=0.25,
    ),
)


def samples_for(speaker: SynthSpeaker, count: int, *, start: int = 0, **kwargs) -> list[bytes]:
    """`count` different utterances by one speaker."""
    return [speaker.utterance(seed=start + index, **kwargs) for index in range(count)]
