"""`docs/LIVE_TEST_REPORT.md`, written from a run rather than from memory.

Every number in the report comes out of `results.json`, which comes out of a
run that actually happened. Nothing here can be edited into being green: if a
capability had no scenarios, the table says `n/a` and not `100 %`.
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import Any

from .report import ScenarioResult, latency_table

REPO_ROOT = Path(__file__).resolve().parents[2]
REPORT = REPO_ROOT / "docs" / "LIVE_TEST_REPORT.md"

THRESHOLD_TEXT = {
    "intent_accuracy": "≥ 95 %",
    "wer_mean": "≤ 10 %",
    "routing_accuracy": "≥ 90 %",
    "round_trip_median": "≤ 2 s",
}


def _pct(value: Any) -> str:
    return "n/a" if value is None else f"{float(value) * 100:.1f} %"


def _secs(value: Any) -> str:
    return "n/a" if value is None else f"{float(value):.2f} s"


def write_report(payload: dict[str, Any], results: list[ScenarioResult],
                 path: Path | None = None) -> Path:
    totals = payload["totals"]
    latencies = payload.get("latency") or latency_table(results)
    when = _dt.datetime.now().strftime("%Y-%m-%d")
    mode = payload.get("mode", "full")

    lines: list[str] = [
        "# Live test report",
        "",
        f"Generated by `python3 -m testing.live.runner --{mode} --write-report` on {when}. "
        "Every number below is measured; nothing in this file is written by hand.",
        "",
        "The rig talks to Jarvis the way a person does: the user's speech is synthesised "
        "locally with Piper in `en_US-amy-low` (Jarvis answers in `en_GB-alan-medium`, so no "
        "transcript can be attributed to the wrong side), delivered through the audio-input "
        "API and through a real headless browser's microphone, and Jarvis's spoken replies "
        "are transcribed back with the same Whisper the system itself uses.",
        "",
        "## Headline",
        "",
        "| measure | value | threshold (full mode) |",
        "|---|---|---|",
        f"| scenarios passed | {totals['scenarios_passed']}/{totals['scenarios']} | all |",
        f"| turns passed | {totals['turns_passed']}/{totals['turns']} | all |",
        f"| intent accuracy | {_pct(totals.get('intent_accuracy'))} | "
        f"{THRESHOLD_TEXT['intent_accuracy']} |",
        f"| word error rate (mean of {totals.get('wer_samples', 0)}) | "
        f"{_pct(totals.get('wer_mean'))} | {THRESHOLD_TEXT['wer_mean']} |",
        f"| worst single WER | {_pct(totals.get('wer_max'))} | — |",
        f"| routing accuracy ({totals.get('routing_samples', 0)} samples) | "
        f"{_pct(totals.get('routing_accuracy'))} | {THRESHOLD_TEXT['routing_accuracy']} |",
        f"| median round trip | {_secs(totals.get('round_trip_median'))} | "
        f"{THRESHOLD_TEXT['round_trip_median']} |",
        f"| 95th percentile round trip | {_secs(totals.get('round_trip_p95'))} | — |",
        "",
        "## Per capability",
        "",
        "| capability | scenarios | passed | rate |",
        "|---|---|---|---|",
    ]
    for capability, row in sorted(totals["by_capability"].items()):
        rate = None if not row["total"] else row["passed"] / row["total"]
        lines.append(
            f"| {capability} | {row['total']} | {row['passed']} | {_pct(rate)} |"
        )

    lines += [
        "",
        "## Latency, by stage",
        "",
        "Measured at the client, on arrival — what a person waits for, not what a server "
        "clock says it was ready.",
        "",
        "| stage | samples | median | p95 |",
        "|---|---|---|---|",
    ]
    for stage, row in latencies.items():
        lines.append(
            f"| {stage} | {row['n']} | {_secs(row['median'])} | {_secs(row['p95'])} |"
        )

    failed = [r for r in results if not r.ok]
    lines += ["", "## What failed", ""]
    if not failed:
        lines.append("Nothing. Every selected scenario passed.")
    else:
        lines.append("| scenario | variant | gated on | what went wrong |")
        lines.append("|---|---|---|---|")
        for result in failed:
            reason = result.error or "; ".join(
                failure for turn in result.turns for failure in turn.failures
            )
            lines.append(
                f"| {result.name} | {result.variant} | {result.gated_on or '—'} | "
                f"{reason[:300].replace('|', '¦')} |"
            )

    judged = payload.get("judge") or []
    if judged:
        lines += [
            "",
            "## What the judge said",
            "",
            "A local model grades only the criteria a deterministic check cannot express. "
            "Every verdict it gave in this run, with its reason — a suite that passes for "
            "silly reasons should read as silly.",
            "",
            "| verdict | criterion | why |",
            "|---|---|---|",
        ]
        for verdict in judged[:60]:
            mark = "ok" if verdict.get("ok") else "**no**"
            lines.append(
                f"| {mark} | {str(verdict.get('criterion'))[:80].replace('|', '¦')} | "
                f"{str(verdict.get('why'))[:120].replace('|', '¦')} |"
            )

    lines += [
        "",
        "## Open issues",
        "",
        "`ISSUES.md` holds every defect this rig found, with the regression scenario added "
        "for it. Anything still open is listed there; anything that needs the operator "
        "rather than the code is in `BLOCKERS.md`.",
        "",
    ]

    target = path or REPORT
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines), encoding="utf-8")
    return target
